#!/usr/bin/env python3
import argparse
from ampwrapper.utils import get_environment, BOLD, wrap, DEFAULT

def main():
    env_path = get_environment()

    parser = argparse.ArgumentParser()
    parser.add_argument("-env", "--env-path", action="store_true", help="print the present env path")
    args = parser.parse_args()

    if args.env_path:
        print(f'The present env path is: {env_path}')

if __name__ == "__main__":
    main()
