#!/usr/bin/env python3
import argparse
from ampwrapper.utils import get_environment, BOLD, wrap, DEFAULT
env_path = get_environment()
parser = argparse.ArgumentParser()

def main():
    pass


if __name__ == "__main__":
    main()
